services:
  - type: web_service
    name: tetgame-backend
    env: docker
    repo: https://github.com/thomas-tran-fullstack/TetGame
    branch: main
    dockerfile: ./Dockerfile
    healthCheckPath: /actuator/health

databases:
  - name: tetgame-db
    databaseName: tetgame
    plan: starter

addons:
  - type: redis
    name: tetgame-redis
    plan: starter